#!/usr/bin/env python3
import sys
import getopt

############################################################################
# Main gateway: 
#############################################################################
# usage
def main_usage():
    print("""
Usage : vt3d <action> [options ]
          -h/--help           show this short usage
Action:
          -------------------------------------------------------------------------------
          version 1.0:
          MEP                   Maximun Expression Projection. (suit 3D structure to 2D)
          AnySlice              Extract 2D slice from any angle.
          AtlasBrowser          Browser your data interactively.
          Auxiliary             More auxiliary tools

          -------------------------------------------------------------------------------

Detail usage of each action:
        vt3d <action> -h
""")

# logic codes
if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] in ( "-h" , "--help" ):
        main_usage()
        exit(0)
    elif len(sys.argv) < 2 or not sys.argv[1] in ( "MEP",
                                                   "AnySlice",
                                                   "Auxiliary",
                                                   "AtlasBrowser",
                                                   ):
        main_usage()
        exit(1)
    elif sys.argv[1] == "MEP" :
        from vt3d_tools.mep import mep_main
        mep_main(sys.argv[2:])
        exit(0)
    elif sys.argv[1] == "AnySlice" :
        from vt3d_tools.anyslice import anyslice_main
        anyslice_main(sys.argv[2:])
        exit(0)
    elif sys.argv[1] == "Auxiliary" :
        from vt3d_tools.auxiliary import Auxiliary_main 
        Auxiliary_main(sys.argv[2:])
        exit(0)
    elif sys.argv[1] == "AtlasBrowser" :
        from vt3d_tools.atlas_browser import AtlasBrowser_main
        AtlasBrowser_main(sys.argv[2:])
    else:
        main_usage()
        exit(1)
