#!/usr/bin/env python3
import sys
import getopt
import time

############################################################################
# Main gateway: 
#############################################################################
# usage
def main_usage():
    print("""
Usage : vt3d <action> [options ]
          -h/--help           show this short usage
Action:
          -------------------------------------------------------------------------------
          MEP                   Maximun Expression Projection. (suit 3D structure to 2D)
          AnySlice              Extract 2D slice from any angle.
          GrayScaleTif          Generate 3D TIFF gray scale image as input of Slicer3D.
          WebCache              Generate cache files for WebCache action.
          WebServer             Start the atlas server for VT3D_Browse in WebCache folder.
          -------------------------------------------------------------------------------

Detail usage of each action:
        vt3d <action> -h
""")

#          ROI                   3D ROI
#          PosAction             shift/rotate/scale the cell postions
#                                                   "ROI",
#                                                   "PosAction",

# logic codes
if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] in ( "-h" , "--help" ):
        main_usage()
        exit(0)
    elif len(sys.argv) < 2 or not sys.argv[1] in ( "MEP",
                                                   "AnySlice",
                                                   "GrayScaleTif",
                                                   "WebCache",
                                                   "WebServer",
                                                   ):
        main_usage()
        exit(1)
    elif sys.argv[1] == "MEP" :
        from vt3d_tools.mep import mep_main
        mep_main(sys.argv[2:])
        exit(0)
    elif sys.argv[1] == "AnySlice" :
        from vt3d_tools.anyslice import anyslice_main
        anyslice_main(sys.argv[2:])
        exit(0)
    elif sys.argv[1] == "GrayScaleTif" :
        from vt3d_tools.grayscaletif import grayscaletif_main
        grayscaletif_main(sys.argv[2:])
        exit(0)
    elif sys.argv[1] == "WebCache" :
        from vt3d_tools.webcache import webcache_main
        webcache_main(sys.argv[2:])
        exit(0)
    elif sys.argv[1] == "WebServer" :
        from vt3d_tools.webserver import webserver_main
        webserver_main(sys.argv[2:])
        exit(0)
    else:
        main_usage()
        exit(1)
